# Generated by Django 6.0.6 on 2026-07-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_alter_resume_education_alter_resume_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_assist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_resume',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_review',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
