# Generated by Django 6.0.6 on 2026-07-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_ai_assist_resume_ai_resume_resume_ai_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_cover_letter',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
