# Generated by Django 6.0.6 on 2026-07-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_ai_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='edited_cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
