# Generated by Django 6.0.6 on 2026-07-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resume_edited_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
